services:
  - type: web
    name: fashion-store
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fashion-store-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: your_email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your_app_password

databases:
  - name: fashion-store-db
    databaseName: fashionstoredb
    user: fashionstore_user
