services:
  - type: web
    name: fashion-store
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: fashion-store-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
    buildpacks:
      - heroku/python

databases:
  - name: fashion-store-db
    databaseName: fashionstoredb
    user: fashionstore_user
